In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf

In [27]:
# get sp500 data 
sp500 = yf.download('^GSPC', start='2000-01-06')
sp500

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2000-01-06,1402.109985,1411.900024,1392.099976,1403.449951,1403.449951,1092300000
2000-01-07,1403.449951,1441.469971,1400.729980,1441.469971,1441.469971,1225200000
2000-01-10,1441.469971,1464.359985,1441.469971,1457.599976,1457.599976,1064800000
2000-01-11,1457.599976,1458.660034,1434.420044,1438.560059,1438.560059,1014000000
2000-01-12,1438.560059,1442.599976,1427.079956,1432.250000,1432.250000,974600000
...,...,...,...,...,...,...
2024-05-01,5029.029785,5096.120117,5013.450195,5018.390137,5018.390137,4544170000
2024-05-02,5049.319824,5073.209961,5011.049805,5064.200195,5064.200195,4381660000
2024-05-03,5122.779785,5139.120117,5101.220215,5127.790039,5127.790039,3924990000
2024-05-06,5142.419922,5181.000000,5142.419922,5180.740234,5180.740234,3683250000
2024-05-07,5187.200195,5197.500000,5184.109863,5192.850098,5192.850098,991709969

In [25]:
df = pd.read_csv("sentiment.csv")
df

In [29]:
# for all columns in df (except date) rename the column to the column name + _sentiment
for col in df.columns[1:]:
    df.rename(columns={col: col + "_sentiment"}, inplace=True)

In [37]:
# convert the date column to datetime for df and sp500
df['Date'] = pd.to_datetime(df['Date'])
sp500['Date'] = pd.to_datetime(sp500.index)
# rename the index to ind
sp500.index.name = 'ind'

In [38]:
# merge the two dataframes on the date column
merged = pd.merge(sp500, df, on='Date')

In [39]:
merged

,Open,High,Low,Close,Adj Close,Volume,Date,Bullish_sentiment,Neutral_sentiment,Bearish_sentiment,Total_sentiment,Mov Avg_sentiment,Spread_sentiment,Average_sentiment,+St. Dev._sentiment,- St. Dev._sentiment,High_sentiment,Low_sentiment,Close_sentiment
0,1402.109985,1411.900024,1392.099976,1403.449951,1403.449951,1092300000,2000-01-06,0.750000,0.116600,0.133300,0.999900,0.582500,0.616700,0.376108,0.477314,0.274901,1478.00,1377.68,1441.47
1,1432.250000,1454.199951,1432.250000,1449.680054,1449.680054,1030400000,2000-01-13,0.592600,0.222200,0.185200,1.000000,0.599075,0.407400,0.376108,0.477314,0.274901,1473.00,1427.08,1465.15
2,1455.900024,1465.709961,1438.540039,1445.569946,1445.569946,1100700000,2000-01-20,0.571400,0.250000,0.178600,1.000000,0.601750,0.392800,0.376108,0.477314,0.274901,1465.71,1438.54,1441.36
3,1404.089966,1418.859985,1370.989990,1398.560059,1398.560059,1129500000,2000-01-27,0.537000,0.259300,0.203700,1.000000,0.591375,0.333300,0.376108,0.477314,0.274901,1454.09,1356.20,1360.16
4,1409.119995,1425.780029,1398.520020,1424.969971,1424.969971,1146500000,2000-02-03,0.511100,0.244400,0.244400,0.999900,0.577763,0.266700,0.376108,0.477314,0.274901,1435.91,1350.14,1424.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1236,5244.049805,5256.589844,5146.060059,5147.209961,5147.209961,4075680000,2024-04-04,0.472868,0.304910,0.222222,1.000000,0.463833,0.250646,0.376108,0.477314,0.274901,5264.85,5184.05,5211.49
1237,5172.950195,5211.779785,5138.770020,5199.060059,5199.060059,3509380000,2024-04-11,0.434426,0.325137,0.240437,1.000000,0.465422,0.193989,0.376108,0.477314,0.274901,5222.18,5188.70,5160.64
1238,5031.520020,5056.660156,5001.890137,5011.120117,5011.120117,3619760000,2024-04-18,0.382749,0.277628,0.339623,1.000000,0.457919,0.043126,0.376108,0.477314,0.274901,5175.03,5007.25,5022.21
1239,5019.879883,5057.750000,4990.580078,5048.419922,5048.419922,3958050000,2024-04-25,0.321337,0.339332,0.339332,1.000001,0.439965,-0.017995,0.376108,0.477314,0.274901,5089.48,4953.56,5071.63
1240,5049.319824,5073.209961,5011.049805,5064.200195,5064.200195,4381660000,2024-05-02,0.384858,0.290221,0.324921,1.000000,0.423404,0.059937,0.376108,0.477314,0.274901,5123.49,4990.58,5018.39

In [40]:
# make date the first column
a = merged.pop('Date')
merged.insert(0, 'Date', a)
merged

,Date,Open,High,Low,Close,Adj Close,Volume,Bullish_sentiment,Neutral_sentiment,Bearish_sentiment,Total_sentiment,Mov Avg_sentiment,Spread_sentiment,Average_sentiment,+St. Dev._sentiment,- St. Dev._sentiment,High_sentiment,Low_sentiment,Close_sentiment
0,2000-01-06,1402.109985,1411.900024,1392.099976,1403.449951,1403.449951,1092300000,0.750000,0.116600,0.133300,0.999900,0.582500,0.616700,0.376108,0.477314,0.274901,1478.00,1377.68,1441.47
1,2000-01-13,1432.250000,1454.199951,1432.250000,1449.680054,1449.680054,1030400000,0.592600,0.222200,0.185200,1.000000,0.599075,0.407400,0.376108,0.477314,0.274901,1473.00,1427.08,1465.15
2,2000-01-20,1455.900024,1465.709961,1438.540039,1445.569946,1445.569946,1100700000,0.571400,0.250000,0.178600,1.000000,0.601750,0.392800,0.376108,0.477314,0.274901,1465.71,1438.54,1441.36
3,2000-01-27,1404.089966,1418.859985,1370.989990,1398.560059,1398.560059,1129500000,0.537000,0.259300,0.203700,1.000000,0.591375,0.333300,0.376108,0.477314,0.274901,1454.09,1356.20,1360.16
4,2000-02-03,1409.119995,1425.780029,1398.520020,1424.969971,1424.969971,1146500000,0.511100,0.244400,0.244400,0.999900,0.577763,0.266700,0.376108,0.477314,0.274901,1435.91,1350.14,1424.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1236,2024-04-04,5244.049805,5256.589844,5146.060059,5147.209961,5147.209961,4075680000,0.472868,0.304910,0.222222,1.000000,0.463833,0.250646,0.376108,0.477314,0.274901,5264.85,5184.05,5211.49
1237,2024-04-11,5172.950195,5211.779785,5138.770020,5199.060059,5199.060059,3509380000,0.434426,0.325137,0.240437,1.000000,0.465422,0.193989,0.376108,0.477314,0.274901,5222.18,5188.70,5160.64
1238,2024-04-18,5031.520020,5056.660156,5001.890137,5011.120117,5011.120117,3619760000,0.382749,0.277628,0.339623,1.000000,0.457919,0.043126,0.376108,0.477314,0.274901,5175.03,5007.25,5022.21
1239,2024-04-25,5019.879883,5057.750000,4990.580078,5048.419922,5048.419922,3958050000,0.321337,0.339332,0.339332,1.000001,0.439965,-0.017995,0.376108,0.477314,0.274901,5089.48,4953.56,5071.63
1240,2024-05-02,5049.319824,5073.209961,5011.049805,5064.200195,5064.200195,4381660000,0.384858,0.290221,0.324921,1.000000,0.423404,0.059937,0.376108,0.477314,0.274901,5123.49,4990.58,5018.39

In [42]:
# save the merged dataframe to a csv file
#merged.to_csv('fulldata.csv', index=False)